name: Publish Package to npm

on:
  release:
    types: [created]
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for running the workflow"
        required: false
        default: "Re-building manual"

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Publish to npm
        run: |
          VERSION=$(node -p "require('./package.json').version")
          if [[ "$VERSION" =~ .*(alpha|beta|rc).* ]]; then
            echo "Publishing a prerelease version with tag beta..."
            npm publish --tag beta
          else
            echo "Publishing a stable version..."
            npm publish
          fi
